// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
        default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCptx2yPw9O4NHVEU0pUGUI3XdIPQalW-8',
    appId: '1:939845773497:web:d737544ae834c7781f1368',
    messagingSenderId: '939845773497',
    projectId: 'projectmatch-52469',
    authDomain: 'projectmatch-52469.firebaseapp.com',
    storageBucket: 'projectmatch-52469.firebasestorage.app',
    measurementId: 'G-3XL9F8XX7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACmsY8DQQ-Q2530DRMLyi2C_P0cj7TKGo',
    appId: '1:939845773497:android:b37a3aa71320d0091f1368',
    messagingSenderId: '939845773497',
    projectId: 'projectmatch-52469',
    storageBucket: 'projectmatch-52469.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK5PxY2j8e7BYStK0B-d9LLPLl8fZjO8Y',
    appId: '1:939845773497:ios:afe7d6e25d6be19c1f1368',
    messagingSenderId: '939845773497',
    projectId: 'projectmatch-52469',
    storageBucket: 'projectmatch-52469.firebasestorage.app',
    iosBundleId: 'com.example.projectMatch',
  );
}
